"""Initailization

Revision ID: b6262e5f897c
Revises: 
Create Date: 2023-04-29 19:16:27.427707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6262e5f897c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('is_deleted', sa.TIMESTAMP(), nullable=True))
    op.add_column('Users', sa.Column('is_deleted', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_deleted')
    op.drop_column('Tasks', 'is_deleted')
    # ### end Alembic commands ###
