"""group id nullabe

Revision ID: de0a8c0fc2fb
Revises: 04774bcfad99
Create Date: 2023-05-12 22:02:54.953046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0a8c0fc2fb'
down_revision = '04774bcfad99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
